<?php
/**
 * CreateDomainRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dimer47\LaravelForgeSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateDomainRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateDomainRequest
 * @package     Dimer47\LaravelForgeSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateDomainRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateDomainRequest"
     */
    public function testCreateDomainRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_wildcard_subdomains"
     */
    public function testPropertyAllowWildcardSubdomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "www_redirect_type"
     */
    public function testPropertyWwwRedirectType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
