<?php
/**
 * CreateServerRequestCustomTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dimer47\LaravelForgeSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateServerRequestCustomTest Class Doc Comment
 *
 * @category    Class
 * @description CreateServerRequestCustom
 * @package     Dimer47\LaravelForgeSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateServerRequestCustomTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateServerRequestCustom"
     */
    public function testCreateServerRequestCustom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "private_ip_address"
     */
    public function testPropertyPrivateIpAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssh_port"
     */
    public function testPropertySshPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "behind_nat"
     */
    public function testPropertyBehindNat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nat_ssh_port"
     */
    public function testPropertyNatSshPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
