<?php
/**
 * CreateSiteRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dimer47\LaravelForgeSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateSiteRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateSiteRequest
 * @package     Dimer47\LaravelForgeSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateSiteRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateSiteRequest"
     */
    public function testCreateSiteRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domain_mode"
     */
    public function testPropertyDomainMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "www_redirect_type"
     */
    public function testPropertyWwwRedirectType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_wildcard_subdomains"
     */
    public function testPropertyAllowWildcardSubdomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "root_directory"
     */
    public function testPropertyRootDirectory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "web_directory"
     */
    public function testPropertyWebDirectory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_isolated"
     */
    public function testPropertyIsIsolated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isolated_user"
     */
    public function testPropertyIsolatedUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "php_version"
     */
    public function testPropertyPhpVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "zero_downtime_deployments"
     */
    public function testPropertyZeroDowntimeDeployments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nginx_template_id"
     */
    public function testPropertyNginxTemplateId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_control_provider"
     */
    public function testPropertySourceControlProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repository"
     */
    public function testPropertyRepository()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "database_id"
     */
    public function testPropertyDatabaseId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "database_user_id"
     */
    public function testPropertyDatabaseUserId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statamic_setup"
     */
    public function testPropertyStatamicSetup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statamic_starter_kit"
     */
    public function testPropertyStatamicStarterKit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statamic_super_user_email"
     */
    public function testPropertyStatamicSuperUserEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statamic_super_user_password"
     */
    public function testPropertyStatamicSuperUserPassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "install_composer_dependencies"
     */
    public function testPropertyInstallComposerDependencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "generate_deploy_key"
     */
    public function testPropertyGenerateDeployKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "public_deploy_key"
     */
    public function testPropertyPublicDeployKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "private_deploy_key"
     */
    public function testPropertyPrivateDeployKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "frontend_package_manager"
     */
    public function testPropertyFrontendPackageManager()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "frontend_build_command"
     */
    public function testPropertyFrontendBuildCommand()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nuxt_next_mode"
     */
    public function testPropertyNuxtNextMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nuxt_next_port"
     */
    public function testPropertyNuxtNextPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "push_to_deploy"
     */
    public function testPropertyPushToDeploy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shared_paths"
     */
    public function testPropertySharedPaths()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
