<?php
/**
 * BackupsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BackupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BackupsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersDatabaseBackupsDestroy
     *
     * Delete backup configuration.
     *
     */
    public function testOrganizationsServersDatabaseBackupsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsIndex
     *
     * List backup configurations.
     *
     */
    public function testOrganizationsServersDatabaseBackupsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsInstancesDestroy
     *
     * Delete backup.
     *
     */
    public function testOrganizationsServersDatabaseBackupsInstancesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsInstancesIndex
     *
     * List backups.
     *
     */
    public function testOrganizationsServersDatabaseBackupsInstancesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsInstancesRestoresStore
     *
     * Create a database restore from backup.
     *
     */
    public function testOrganizationsServersDatabaseBackupsInstancesRestoresStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsInstancesShow
     *
     * Get backup.
     *
     */
    public function testOrganizationsServersDatabaseBackupsInstancesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsInstancesStore
     *
     * Create backup.
     *
     */
    public function testOrganizationsServersDatabaseBackupsInstancesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsShow
     *
     * Get backup configuration.
     *
     */
    public function testOrganizationsServersDatabaseBackupsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsStore
     *
     * Create backup configuration.
     *
     */
    public function testOrganizationsServersDatabaseBackupsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseBackupsUpdate
     *
     * Update backup configuration.
     *
     */
    public function testOrganizationsServersDatabaseBackupsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
