<?php
/**
 * DatabasesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DatabasesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatabasesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersDatabasePasswordUpdate
     *
     * Update the password for the database.
     *
     */
    public function testOrganizationsServersDatabasePasswordUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseSchemasDestroy
     *
     * Delete database schema.
     *
     */
    public function testOrganizationsServersDatabaseSchemasDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseSchemasIndex
     *
     * List database schemas.
     *
     */
    public function testOrganizationsServersDatabaseSchemasIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseSchemasShow
     *
     * Get database schema.
     *
     */
    public function testOrganizationsServersDatabaseSchemasShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseSchemasStore
     *
     * Create database schema.
     *
     */
    public function testOrganizationsServersDatabaseSchemasStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseSchemasSynchronizationsStore
     *
     * Update database schemas.
     *
     */
    public function testOrganizationsServersDatabaseSchemasSynchronizationsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseUsersDestroy
     *
     * Delete database user.
     *
     */
    public function testOrganizationsServersDatabaseUsersDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseUsersIndex
     *
     * List database users.
     *
     */
    public function testOrganizationsServersDatabaseUsersIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseUsersShow
     *
     * Get database user.
     *
     */
    public function testOrganizationsServersDatabaseUsersShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseUsersStore
     *
     * Create database user.
     *
     */
    public function testOrganizationsServersDatabaseUsersStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDatabaseUsersUpdate
     *
     * Update database user.
     *
     */
    public function testOrganizationsServersDatabaseUsersUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
