<?php
/**
 * DeploymentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeploymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeploymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersSitesDeploymentsDeployHookShow
     *
     * Get the deployment trigger URL.
     *
     */
    public function testOrganizationsServersSitesDeploymentsDeployHookShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsDeployHookUpdate
     *
     * Update deployment trigger URL.
     *
     */
    public function testOrganizationsServersSitesDeploymentsDeployHookUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsIndex
     *
     * List deployments.
     *
     */
    public function testOrganizationsServersSitesDeploymentsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsLogShow
     *
     * Get deployment output.
     *
     */
    public function testOrganizationsServersSitesDeploymentsLogShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsPushToDeployDestroy
     *
     * Delete push to deploy configuration.
     *
     */
    public function testOrganizationsServersSitesDeploymentsPushToDeployDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsPushToDeployStore
     *
     * Create push to deploy configuration.
     *
     */
    public function testOrganizationsServersSitesDeploymentsPushToDeployStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsScriptShow
     *
     * Get deployment script.
     *
     */
    public function testOrganizationsServersSitesDeploymentsScriptShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsScriptUpdate
     *
     * Update deployment script.
     *
     */
    public function testOrganizationsServersSitesDeploymentsScriptUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsShow
     *
     * Get deployment.
     *
     */
    public function testOrganizationsServersSitesDeploymentsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsStatusDestroy
     *
     * Update deployment state.
     *
     */
    public function testOrganizationsServersSitesDeploymentsStatusDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsStatusShow
     *
     * Get deployment status.
     *
     */
    public function testOrganizationsServersSitesDeploymentsStatusShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDeploymentsStore
     *
     * Create deployment.
     *
     */
    public function testOrganizationsServersSitesDeploymentsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesWebhooksDestroy
     *
     * Delete site webhook.
     *
     */
    public function testOrganizationsServersSitesWebhooksDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesWebhooksIndex
     *
     * List site webhooks.
     *
     */
    public function testOrganizationsServersSitesWebhooksIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesWebhooksShow
     *
     * Get site webhook.
     *
     */
    public function testOrganizationsServersSitesWebhooksShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesWebhooksStore
     *
     * Create site webhook.
     *
     */
    public function testOrganizationsServersSitesWebhooksStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
