<?php
/**
 * FirewallRulesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FirewallRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FirewallRulesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersFirewallRulesDestroy
     *
     * Delete server firewall rule.
     *
     */
    public function testOrganizationsServersFirewallRulesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersFirewallRulesIndex
     *
     * List server firewall rules.
     *
     */
    public function testOrganizationsServersFirewallRulesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersFirewallRulesShow
     *
     * Get server firewall rule.
     *
     */
    public function testOrganizationsServersFirewallRulesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersFirewallRulesStore
     *
     * Create server firewall rule.
     *
     */
    public function testOrganizationsServersFirewallRulesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
