<?php
/**
 * IntegrationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IntegrationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersSitesIntegrationsHorizonDestroy
     *
     * Delete Laravel Horizon integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsHorizonDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsHorizonShow
     *
     * Get Laravel Horizon integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsHorizonShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsHorizonStore
     *
     * Create Laravel Horizon integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsHorizonStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsInertiaShow
     *
     * Get Inertia integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsInertiaShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsInertiaStore
     *
     * Create Inertia integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsInertiaStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelMaintenanceDestroy
     *
     * Delete Laravel Maintenance integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelMaintenanceDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelMaintenanceShow
     *
     * Get Laravel Maintenance integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelMaintenanceShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelMaintenanceStore
     *
     * Create Laravel Maintenance integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelMaintenanceStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelSchedulerDestroy
     *
     * Delete Laravel Scheduler integration job.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelSchedulerDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelSchedulerShow
     *
     * Get Laravel Scheduler integration job.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelSchedulerShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsLaravelSchedulerStore
     *
     * Create Laravel Scheduler integration job.
     *
     */
    public function testOrganizationsServersSitesIntegrationsLaravelSchedulerStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsOctaneDestroy
     *
     * Delete Laravel Octane integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsOctaneDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsOctaneShow
     *
     * Get Laravel Octane integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsOctaneShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsOctaneStore
     *
     * Create Laravel Octane integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsOctaneStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsPulseDestroy
     *
     * Delete Laravel Pulse integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsPulseDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsPulseShow
     *
     * Get Laravel Pulse integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsPulseShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsPulseStore
     *
     * Create Laravel Pulse integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsPulseStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsReverbDestroy
     *
     * Delete Laravel Reverb integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsReverbDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsReverbShow
     *
     * Get Laravel Reverb integration status.
     *
     */
    public function testOrganizationsServersSitesIntegrationsReverbShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIntegrationsReverbStore
     *
     * Create Laravel Reverb integration.
     *
     */
    public function testOrganizationsServersSitesIntegrationsReverbStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
