<?php
/**
 * RecipesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecipesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecipesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for forgeRecipesIndex
     *
     * List Forge's recipes.
     *
     */
    public function testForgeRecipesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forgeRecipesRunsStore
     *
     * Create Forge recipe run.
     *
     */
    public function testForgeRecipesRunsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forgeRecipesShow
     *
     * Get Forge recipe.
     *
     */
    public function testForgeRecipesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationRecipesStore
     *
     * Create recipe.
     *
     */
    public function testOrganizationRecipesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesDestroy
     *
     * Delete recipe.
     *
     */
    public function testOrganizationsRecipesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesIndex
     *
     * List organization recipes.
     *
     */
    public function testOrganizationsRecipesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesRunsIndex
     *
     * List recipe runs.
     *
     */
    public function testOrganizationsRecipesRunsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesRunsShow
     *
     * Get recipe run.
     *
     */
    public function testOrganizationsRecipesRunsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesRunsStore
     *
     * Create recipe run.
     *
     */
    public function testOrganizationsRecipesRunsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesShow
     *
     * Get recipe.
     *
     */
    public function testOrganizationsRecipesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsRecipesUpdate
     *
     * Update recipe.
     *
     */
    public function testOrganizationsRecipesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsRecipesDestroy
     *
     * Delete a recipe share.
     *
     */
    public function testOrganizationsTeamsRecipesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsRecipesIndex
     *
     * List team recipes.
     *
     */
    public function testOrganizationsTeamsRecipesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsRecipesStore
     *
     * Share recipe with the team.
     *
     */
    public function testOrganizationsTeamsRecipesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
