<?php
/**
 * ScheduledJobsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ScheduledJobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduledJobsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersScheduledJobsDestroy
     *
     * Delete scheduled job.
     *
     */
    public function testOrganizationsServersScheduledJobsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersScheduledJobsIndex
     *
     * List server scheduled jobs.
     *
     */
    public function testOrganizationsServersScheduledJobsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersScheduledJobsOutputsShow
     *
     * Get scheduled job output.
     *
     */
    public function testOrganizationsServersScheduledJobsOutputsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersScheduledJobsShow
     *
     * Get scheduled job.
     *
     */
    public function testOrganizationsServersScheduledJobsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersScheduledJobsStore
     *
     * Create scheduled job.
     *
     */
    public function testOrganizationsServersScheduledJobsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesScheduledJobsDestroy
     *
     * Delete site scheduled job.
     *
     */
    public function testOrganizationsServersSitesScheduledJobsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesScheduledJobsIndex
     *
     * List site scheduled jobs.
     *
     */
    public function testOrganizationsServersSitesScheduledJobsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesScheduledJobsOutputsShow
     *
     * Get site scheduled job output.
     *
     */
    public function testOrganizationsServersSitesScheduledJobsOutputsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesScheduledJobsShow
     *
     * Get site scheduled job.
     *
     */
    public function testOrganizationsServersSitesScheduledJobsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesScheduledJobsStore
     *
     * Create site scheduled job.
     *
     */
    public function testOrganizationsServersSitesScheduledJobsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
