<?php
/**
 * SecurityRulesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SecurityRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SecurityRulesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersSitesSecurityRulesDestroy
     *
     * Delete site security rule.
     *
     */
    public function testOrganizationsServersSitesSecurityRulesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesSecurityRulesIndex
     *
     * List site security rules.
     *
     */
    public function testOrganizationsServersSitesSecurityRulesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesSecurityRulesShow
     *
     * Get site security rule.
     *
     */
    public function testOrganizationsServersSitesSecurityRulesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesSecurityRulesStore
     *
     * Create site security rule.
     *
     */
    public function testOrganizationsServersSitesSecurityRulesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesSecurityRulesUpdate
     *
     * Update site security rule.
     *
     */
    public function testOrganizationsServersSitesSecurityRulesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
