<?php
/**
 * ServersApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersActionsStore
     *
     * Create server action.
     *
     */
    public function testOrganizationsServersActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersArchivesDestroy
     *
     * Delete archived server.
     *
     */
    public function testOrganizationsServersArchivesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersArchivesIndex
     *
     * List archived servers.
     *
     */
    public function testOrganizationsServersArchivesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersArchivesStore
     *
     * Create an archived server.
     *
     */
    public function testOrganizationsServersArchivesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersBackgroundProcessesActionsStore
     *
     * Perform an action on a server background process.
     *
     */
    public function testOrganizationsServersBackgroundProcessesActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersDestroy
     *
     * Delete server.
     *
     */
    public function testOrganizationsServersDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersEventsIndex
     *
     * List server events.
     *
     */
    public function testOrganizationsServersEventsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersEventsOutputShow
     *
     * Get server event output.
     *
     */
    public function testOrganizationsServersEventsOutputShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersEventsShow
     *
     * Get server event.
     *
     */
    public function testOrganizationsServersEventsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersIndex
     *
     * List servers.
     *
     */
    public function testOrganizationsServersIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpCliVersionShow
     *
     * Get PHP CLI version.
     *
     */
    public function testOrganizationsServersPhpCliVersionShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpCliVersionUpdate
     *
     * Update PHP CLI version.
     *
     */
    public function testOrganizationsServersPhpCliVersionUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpMaxExecutionTimeShow
     *
     * Get server PHP max execution time.
     *
     */
    public function testOrganizationsServersPhpMaxExecutionTimeShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpMaxExecutionTimeUpdate
     *
     * Update server PHP max execution time.
     *
     */
    public function testOrganizationsServersPhpMaxExecutionTimeUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpMaxUploadSizeShow
     *
     * Get server PHP max upload size.
     *
     */
    public function testOrganizationsServersPhpMaxUploadSizeShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpMaxUploadSizeUpdate
     *
     * Update server PHP max upload size.
     *
     */
    public function testOrganizationsServersPhpMaxUploadSizeUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpOpcacheDestroy
     *
     * Delete PHP OPcache config.
     *
     */
    public function testOrganizationsServersPhpOpcacheDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpOpcacheShow
     *
     * Get server PHP OPcache status.
     *
     */
    public function testOrganizationsServersPhpOpcacheShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpOpcacheStore
     *
     * Create PHP OPcache config.
     *
     */
    public function testOrganizationsServersPhpOpcacheStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpSiteVersionShow
     *
     * Get PHP site version.
     *
     */
    public function testOrganizationsServersPhpSiteVersionShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpSiteVersionUpdate
     *
     * Update PHP site version.
     *
     */
    public function testOrganizationsServersPhpSiteVersionUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsCliShow
     *
     * Get PHP version CLI config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsCliShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsCliUpdate
     *
     * Update PHP version CLI config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsCliUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsFpmShow
     *
     * Get PHP version FPM config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsFpmShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsFpmUpdate
     *
     * Update PHP version FPM config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsFpmUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsPoolShow
     *
     * Get PHP version pool config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsPoolShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsConfigsPoolUpdate
     *
     * Update PHP version pool config.
     *
     */
    public function testOrganizationsServersPhpVersionsConfigsPoolUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsDestroy
     *
     * Delete installed PHP version.
     *
     */
    public function testOrganizationsServersPhpVersionsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsIndex
     *
     * List PHP versions for server.
     *
     */
    public function testOrganizationsServersPhpVersionsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsShow
     *
     * Get PHP version.
     *
     */
    public function testOrganizationsServersPhpVersionsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsStore
     *
     * Install new PHP version.
     *
     */
    public function testOrganizationsServersPhpVersionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersPhpVersionsUpdate
     *
     * Update installed PHP version.
     *
     */
    public function testOrganizationsServersPhpVersionsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesMysqlActionsStore
     *
     * Perform MySQL action.
     *
     */
    public function testOrganizationsServersServicesMysqlActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesNginxActionsStore
     *
     * Perform Nginx action.
     *
     */
    public function testOrganizationsServersServicesNginxActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesPhpActionsStore
     *
     * Perform PHP action.
     *
     */
    public function testOrganizationsServersServicesPhpActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesPostgresActionsStore
     *
     * Perform Postgres action.
     *
     */
    public function testOrganizationsServersServicesPostgresActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesRedisActionsStore
     *
     * Perform Redis action.
     *
     */
    public function testOrganizationsServersServicesRedisActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersServicesSupervisorActionsStore
     *
     * Perform Supervisor action.
     *
     */
    public function testOrganizationsServersServicesSupervisorActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersShow
     *
     * Get server.
     *
     */
    public function testOrganizationsServersShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersStore
     *
     * Create server.
     *
     */
    public function testOrganizationsServersStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsServersDestroy
     *
     * Delete a server share.
     *
     */
    public function testOrganizationsTeamsServersDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsServersIndex
     *
     * List team servers.
     *
     */
    public function testOrganizationsTeamsServersIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsServersStore
     *
     * Create a new server share.
     *
     */
    public function testOrganizationsTeamsServersStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
