<?php
/**
 * SitesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SitesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SitesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsServersSitesComposerCredentialsDestroy
     *
     * Delete composer credentials for the site.
     *
     */
    public function testOrganizationsServersSitesComposerCredentialsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesComposerCredentialsIndex
     *
     * Get composer credentials for the site.
     *
     */
    public function testOrganizationsServersSitesComposerCredentialsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesComposerCredentialsShow
     *
     * Get composer credential for the site.
     *
     */
    public function testOrganizationsServersSitesComposerCredentialsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesComposerCredentialsStore
     *
     * Create composer credentials for the site.
     *
     */
    public function testOrganizationsServersSitesComposerCredentialsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesComposerCredentialsUpdate
     *
     * Update composer credentials for the site.
     *
     */
    public function testOrganizationsServersSitesComposerCredentialsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDestroy
     *
     * Delete site.
     *
     */
    public function testOrganizationsServersSitesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsActionsStore
     *
     * Create domain action.
     *
     */
    public function testOrganizationsServersSitesDomainsActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsCertificateActionsStore
     *
     * Create domain certificate action.
     *
     */
    public function testOrganizationsServersSitesDomainsCertificateActionsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsCertificateDestroy
     *
     * Delete domain certificate.
     *
     */
    public function testOrganizationsServersSitesDomainsCertificateDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsCertificateShow
     *
     * Get domain certificate.
     *
     */
    public function testOrganizationsServersSitesDomainsCertificateShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsCertificateStore
     *
     * Create domain certificate.
     *
     */
    public function testOrganizationsServersSitesDomainsCertificateStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsConfigurations
     *
     * Get domain DNS configuration.
     *
     */
    public function testOrganizationsServersSitesDomainsConfigurations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsDestroy
     *
     * Delete domain.
     *
     */
    public function testOrganizationsServersSitesDomainsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsIndex
     *
     * List domains.
     *
     */
    public function testOrganizationsServersSitesDomainsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsNginxShow
     *
     * Get domain Nginx configuration.
     *
     */
    public function testOrganizationsServersSitesDomainsNginxShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsNginxUpdate
     *
     * Update domain Nginx configuration.
     *
     */
    public function testOrganizationsServersSitesDomainsNginxUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsShow
     *
     * Get domain.
     *
     */
    public function testOrganizationsServersSitesDomainsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsStore
     *
     * Create domain.
     *
     */
    public function testOrganizationsServersSitesDomainsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesDomainsUpdate
     *
     * Update domain.
     *
     */
    public function testOrganizationsServersSitesDomainsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesEnvironmentShow
     *
     * Get .env content.
     *
     */
    public function testOrganizationsServersSitesEnvironmentShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesEnvironmentUpdate
     *
     * Update .env content.
     *
     */
    public function testOrganizationsServersSitesEnvironmentUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHealthcheckShow
     *
     * Get healthcheck endpoint.
     *
     */
    public function testOrganizationsServersSitesHealthcheckShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHealthcheckUpdate
     *
     * Update healthcheck endpoint.
     *
     */
    public function testOrganizationsServersSitesHealthcheckUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHeartbeatsDestroy
     *
     * Delete heartbeat.
     *
     */
    public function testOrganizationsServersSitesHeartbeatsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHeartbeatsIndex
     *
     * List heartbeats.
     *
     */
    public function testOrganizationsServersSitesHeartbeatsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHeartbeatsShow
     *
     * Get heartbeat.
     *
     */
    public function testOrganizationsServersSitesHeartbeatsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHeartbeatsStore
     *
     * Create heartbeat.
     *
     */
    public function testOrganizationsServersSitesHeartbeatsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesHeartbeatsUpdate
     *
     * Update heartbeat.
     *
     */
    public function testOrganizationsServersSitesHeartbeatsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesIndex
     *
     * List sites for server.
     *
     */
    public function testOrganizationsServersSitesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLoadBalancingNodesIndex
     *
     * List load balancing nodes.
     *
     */
    public function testOrganizationsServersSitesLoadBalancingNodesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLoadBalancingNodesUpdate
     *
     * Update load balancing nodes.
     *
     */
    public function testOrganizationsServersSitesLoadBalancingNodesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsApplicationDestroy
     *
     * Delete site log content.
     *
     */
    public function testOrganizationsServersSitesLogsApplicationDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsApplicationShow
     *
     * Get site log content.
     *
     */
    public function testOrganizationsServersSitesLogsApplicationShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsNginxAccessDestroy
     *
     * Delete Nginx access log content.
     *
     */
    public function testOrganizationsServersSitesLogsNginxAccessDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsNginxAccessShow
     *
     * Get Nginx access log content.
     *
     */
    public function testOrganizationsServersSitesLogsNginxAccessShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsNginxErrorDestroy
     *
     * Delete Nginx error log content.
     *
     */
    public function testOrganizationsServersSitesLogsNginxErrorDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesLogsNginxErrorShow
     *
     * Get Nginx error log content.
     *
     */
    public function testOrganizationsServersSitesLogsNginxErrorShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesNginxShow
     *
     * Get Nginx configuration.
     *
     */
    public function testOrganizationsServersSitesNginxShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesNginxUpdate
     *
     * Update Nginx configuration.
     *
     */
    public function testOrganizationsServersSitesNginxUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesStore
     *
     * Create site.
     *
     */
    public function testOrganizationsServersSitesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsServersSitesUpdate
     *
     * Update site.
     *
     */
    public function testOrganizationsServersSitesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsSitesIndex
     *
     * List sites for Organization.
     *
     */
    public function testOrganizationsSitesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsSitesShow
     *
     * Get site.
     *
     */
    public function testOrganizationsSitesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitesIndex
     *
     * List sites.
     *
     */
    public function testSitesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
