<?php
/**
 * TeamsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forge
 *
 * Laravel Forge - API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dimer47\LaravelForgeSdk\Test\Api;

use \Dimer47\LaravelForgeSdk\Configuration;
use \Dimer47\LaravelForgeSdk\ApiException;
use \Dimer47\LaravelForgeSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dimer47\LaravelForgeSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for organizationsTeamsDestroy
     *
     * Delete team.
     *
     */
    public function testOrganizationsTeamsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsIndex
     *
     * List teams.
     *
     */
    public function testOrganizationsTeamsIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsInvitesDestroy
     *
     * Delete team invitation.
     *
     */
    public function testOrganizationsTeamsInvitesDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsInvitesIndex
     *
     * List team invitations.
     *
     */
    public function testOrganizationsTeamsInvitesIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsInvitesShow
     *
     * Get team invitation.
     *
     */
    public function testOrganizationsTeamsInvitesShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsInvitesStore
     *
     * Create team invite.
     *
     */
    public function testOrganizationsTeamsInvitesStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsMembersDestroy
     *
     * Delete team member.
     *
     */
    public function testOrganizationsTeamsMembersDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsMembersIndex
     *
     * List team members.
     *
     */
    public function testOrganizationsTeamsMembersIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsMembersShow
     *
     * Get team member.
     *
     */
    public function testOrganizationsTeamsMembersShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsMembersUpdate
     *
     * Update team member.
     *
     */
    public function testOrganizationsTeamsMembersUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsShow
     *
     * Get team.
     *
     */
    public function testOrganizationsTeamsShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsStore
     *
     * Create team.
     *
     */
    public function testOrganizationsTeamsStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for organizationsTeamsUpdate
     *
     * Update team.
     *
     */
    public function testOrganizationsTeamsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
